# Generated by Django 3.1 on 2021-10-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20211018_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='opening_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Opening date'),
        ),
    ]
