# Generated by Django 3.1 on 2021-10-27 08:31

import auction.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20211018_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'IN_PROGRESS'), (3, 'CLOSED')], default=auction.enums.AuctionStatusEnum['PENDING'], verbose_name='Auction status'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='type',
            field=models.IntegerField(choices=[(1, 'ENGLISH'), (2, 'DUTCH')], default=auction.enums.AuctionTypeEnum['ENGLISH'], verbose_name='Auction type'),
        ),
    ]
