version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
  
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379
    command: celery -A backend worker -l INFO
    depends_on:
     - db
     - redi

  web:
    build:
      context: .
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=543
      - REDIS_URL=redis://redis:6379
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
     - db
     - redis
     - celery
    
    stdin_open: true
    tty: true
