# Generated by Django 3.1 on 2021-10-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20211027_0831'),
        ('offer', '0002_auto_20211027_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='lot',
        ),
        migrations.AddField(
            model_name='offer',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
            preserve_default=False,
        ),
    ]
