# Generated by Django 3.1 on 2021-10-18 10:16

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='closing_date',
            field=models.DateTimeField(verbose_name='Closing date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='End price'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reserve_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Reserve price'),
        ),
    ]
