# Generated by Django 3.2.8 on 2021-11-11 12:26

from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20211029_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, verbose_name='End price'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='opening_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opening date'),
        ),
    ]
