# Generated by Django 3.2.8 on 2021-11-12 12:00

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20211111_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='End price'),
        ),
    ]
