# Generated by Django 3.2.8 on 2021-12-01 09:33

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_alter_auction_end_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, verbose_name='End price'),
        ),
    ]
