# Generated by Django 3.1 on 2021-10-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
