# Generated by Django 3.1 on 2021-10-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0003_auto_20211025_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
